#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# daemons
exec-once = mako
exec-once = systemctl --user start hyprpolkitagent

# darko mode
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Moga-Cursor'
exec = hyprctl setcursor GoogleDot-Blue 32

# exec-once = $terminal
exec-once = hyprpaper & nm-applet
# eww
exec-once = /home/.bomba/.local/bin/eww/eww open bar
